name: ra_clinic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  contact_add: ^0.0.3
  cupertino_calendar_picker: ^2.2.6
  flutter:
    sdk: flutter

  flutter_phone_direct_caller: ^2.2.1
  flutter_slidable: ^4.0.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  pull_down_button: ^0.10.2
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  intl: ^0.20.2
  syncfusion_flutter_calendar: ^31.2.18
  syncfusion_localizations: ^31.2.18
  hive: ^2.2.3
  flex_color_scheme: ^8.3.1
  supabase_flutter: ^2.10.3
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  connectivity_plus: ^7.0.0
  webdav_client: ^1.2.2
  file_picker: ^10.3.7
  mime: ^2.0.0
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  video_player: ^2.10.1
  fc_native_video_thumbnail: ^0.17.2
  image: ^4.6.0
  flutter_dotenv: ^6.0.0
  syncfusion_flutter_datepicker: ^31.2.18
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
